const appStoreServerNotificationsRowColumns = `
notificationType,
subtype,
notificationUUID,
version,
signedDate,
dataAppAppleId,
dataBundleId,
dataBundleVersion,
dataEnvironment,
dataStatus,
renewalInfoAutoRenewProductId,
renewalInfoAutoRenewStatus,
renewalInfoEnvironment,
renewalInfoExpirationIntent,
renewalInfoGracePeriodExpiresDate,
renewalInfoIsInBillingRetryPeriod,
renewalInfoOfferIdentifier,
renewalInfoOfferType,
renewalInfoOriginalTransactionId,
renewalInfoPriceIncreaseStatus,
renewalInfoProductId,
renewalInfoRecentSubscriptionStartDate,
renewalInfoRenewalDate,
renewalInfoSignedDate,
transactionInfoAppAccountToken,
transactionInfoBundleId,
transactionInfoEnvironment,
transactionInfoExpiresDate,
transactionInfoInAppOwnershipType,
transactionInfoIsUpgraded,
transactionInfoOfferIdentifier,
transactionInfoOfferType,
transactionInfoOriginalPurchaseDate,
transactionInfoOriginalTransactionId,
transactionInfoProductId,
transactionInfoPurchaseDate,
transactionInfoQuantity,
transactionInfoRevocationDate,
transactionInfoRevocationReason,
transactionInfoSignedDate,
transactionInfoSubscriptionGroupIdentifier,
transactionInfoTransactionId,
transactionInfoType,
transactionInfoWebOrderLineItemId
`;

type AppStoreServerNotificationsRowType = {
    notificationType?: string,
    subtype?: string,
    notificationUUID: string,
    version?: string,
    signedDate?: Date,
    dataAppAppleId?: string,
    dataBundleId?: string,
    dataBundleVersion?: number,
    dataEnvironment?: string,
    dataStatus?: number,
    renewalInfoAutoRenewProductId?: string,
    renewalInfoAutoRenewStatus?: number,
    renewalInfoEnvironment?: string,
    renewalInfoExpirationIntent?: number,
    renewalInfoGracePeriodExpiresDate?: Date,
    renewalInfoIsInBillingRetryPeriod?: boolean,
    renewalInfoOfferIdentifier?: string,
    renewalInfoOfferType?: number,
    renewalInfoOriginalTransactionId?: number,
    renewalInfoPriceIncreaseStatus?: number,
    renewalInfoProductId?: string,
    renewalInfoRecentSubscriptionStartDate?: Date,
    renewalInfoRenewalDate?: Date,
    renewalInfoSignedDate?: Date,
    transactionInfoAppAccountToken?: string,
    transactionInfoBundleId?: string,
    transactionInfoEnvironment?: string,
    transactionInfoExpiresDate: Date,
    transactionInfoInAppOwnershipType?: string,
    transactionInfoIsUpgraded?: boolean,
    transactionInfoOfferIdentifier?: string,
    transactionInfoOfferType?: number,
    transactionInfoOriginalPurchaseDate?: Date,
    transactionInfoOriginalTransactionId?: number,
    transactionInfoProductId?: string,
    transactionInfoPurchaseDate?: Date,
    transactionInfoQuantity: number,
    transactionInfoRevocationDate?: Date,
    transactionInfoRevocationReason: number,
    transactionInfoSignedDate?: Date,
    transactionInfoSubscriptionGroupIdentifier?: number,
    transactionInfoTransactionId?: number,
    transactionInfoType?: string,
    transactionInfoWebOrderLineItemId?: number,
};

export { AppStoreServerNotificationsRowType, appStoreServerNotificationsRowColumns };
